### ISSUE TITLE
Make timescale enabled by default 

### ISSUE THREAD

**Issue by Rickyxstar** [thoras-ai/helm-charts#132]
```
metricsCollector:
  persistence:
    enabled: true
    storageClassName: "efs-sc"
  timescale:
    enabled: true
```
